ca::mcgill::ecse211::lab5::Navigation
final int ca.mcgill.ecse211.lab5.Navigation.FORWARD_SPEED
final int ca.mcgill.ecse211.lab5.Navigation.ROTATE_SPEED
final double ca.mcgill.ecse211.lab5.Navigation.SENSOR_DIS
EV3LargeRegulatedMotor ca.mcgill.ecse211.lab5.Navigation.leftMotor
EV3LargeRegulatedMotor ca.mcgill.ecse211.lab5.Navigation.rightMotor
Odometer ca.mcgill.ecse211.lab5.Navigation.odometer
SensorData ca.mcgill.ecse211.lab5.Navigation.data
ca.mcgill.ecse211.lab5.Navigation.Navigation(EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor)
This navigation class constructor sets up our robot to begin navigating a particular map leftMotor The EV3LargeRegulatedMotor instance for our left motor rightMotor The EV3LargeRegulatedMotor instance for our right motor
References ca.mcgill.ecse211.odometer.Odometer.getOdometer, ca.mcgill.ecse211.sensors.SensorData.getSensorData.
void ca.mcgill.ecse211.lab5.Navigation.travelTo(double x, double y, boolean doCorrection)
TravelTo function which takes as arguments the x and y position in cm Will travel to designated position, while constantly updating it's headingWhen avoid=true, the nav thread will handle traveling. If you want to travel without avoidance, this is also possible. In this case, the method in the Navigation class is used. x The x coordinate to travel to (in cm) y The y coordinate to travel to (in cm)
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.lab5.Navigation.turnTo, ca.mcgill.ecse211.lab5.Navigation.convertDistance, ca.mcgill.ecse211.lab5.Lab5.WHEEL_RAD, ca.mcgill.ecse211.lab5.Lab5.TILE, ca.mcgill.ecse211.sensors.SensorData.getDL, ca.mcgill.ecse211.lab5.Navigation.doCorrection.
Referenced by ca.mcgill.ecse211.lab5.Lab5.main, ca.mcgill.ecse211.lab5.Lab5.searchArea.
void ca.mcgill.ecse211.lab5.Navigation.travelBackTo(double x, double y)
void ca.mcgill.ecse211.lab5.Navigation.turnTo(double angle, boolean async)
This method is where the logic for the odometer will run. Use the methods provided from the OdometerData class to implement the odometer. angle The angle we want our robot to turn to (in degrees)
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.lab5.Lab5.WHEEL_RAD, ca.mcgill.ecse211.lab5.Lab5.TRACK.
Referenced by ca.mcgill.ecse211.lab5.Lab5.searchArea, ca.mcgill.ecse211.lab5.LightLocalizer.localize, ca.mcgill.ecse211.lab5.Navigation.travelTo, ca.mcgill.ecse211.lab5.RingSearcher.search, ca.mcgill.ecse211.lab5.UltrasonicLocalizer.localize.
void ca.mcgill.ecse211.lab5.Navigation.doCorrection(double angle)
angle
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.lab5.Lab5.TILE, ca.mcgill.ecse211.odometer.OdometerData.setY, ca.mcgill.ecse211.odometer.OdometerData.setX.
Referenced by ca.mcgill.ecse211.lab5.Navigation.travelTo.
void ca.mcgill.ecse211.lab5.Navigation.rotate(int angle)
Rotate the robot by certain angle angle
References ca.mcgill.ecse211.lab5.Lab5.WHEEL_RAD, ca.mcgill.ecse211.lab5.Lab5.TRACK.
void ca.mcgill.ecse211.lab5.Navigation.stop()
Stop the motor
Referenced by ca.mcgill.ecse211.lab5.RingSearcher.search.
static int ca.mcgill.ecse211.lab5.Navigation.convertDistance(double radius, double distance)
This method allows the conversion of a distance to the total rotation of each wheel need to cover that distance. radius The radius of our wheels distance The distance travelled A converted distance
Referenced by ca.mcgill.ecse211.lab5.LightLocalizer.localize, ca.mcgill.ecse211.lab5.Navigation.travelTo.
static int ca.mcgill.ecse211.lab5.Navigation.convertAngle(double radius, double width, double angle)
This method allows the conversion of an angle value radius The radius of our wheels distance The distance travelled angle The angle to convert A converted angle