ca::mcgill::ecse211::sensors::SensorData
volatile double ca.mcgill.ecse211.sensors.SensorData.light
volatile double ca.mcgill.ecse211.sensors.SensorData.distance
volatile double ca.mcgill.ecse211.sensors.SensorData.angle
volatile int ca.mcgill.ecse211.sensors.SensorData.rgb[][][][]
volatile boolean ca.mcgill.ecse211.sensors.SensorData.isReseting
Condition ca.mcgill.ecse211.sensors.SensorData.doneReseting
volatile int ca.mcgill.ecse211.sensors.SensorData.numberOfIntances
final int ca.mcgill.ecse211.sensors.SensorData.MAX_INSTANCES
Lock ca.mcgill.ecse211.sensors.SensorData.lock
SensorData ca.mcgill.ecse211.sensors.SensorData.sensorData
ca.mcgill.ecse211.sensors.SensorData.SensorData()
Default constructor. The constructor is private. A factory is used instead such that only one instance of this class is ever created.
Referenced by ca.mcgill.ecse211.sensors.SensorData.getSensorData.
static synchronized SensorData ca.mcgill.ecse211.sensors.SensorData.getSensorData()
OdometerData factory. Returns an OdometerData instance and makes sure that only one instance is ever created. If the user tries to instantiate multiple objects, the method throws a MultipleOdometerDataException.An OdometerData object OdometerExceptions
References ca.mcgill.ecse211.sensors.SensorData.SensorData.
Referenced by ca.mcgill.ecse211.lab5.Display.Display, ca.mcgill.ecse211.lab5.Lab5.main, ca.mcgill.ecse211.lab5.LightLocalizer.LightLocalizer, ca.mcgill.ecse211.lab5.Navigation.Navigation, ca.mcgill.ecse211.lab5.RingSearcher.RingSearcher, ca.mcgill.ecse211.lab5.UltrasonicLocalizer.UltrasonicLocalizer.
double [] ca.mcgill.ecse211.sensors.SensorData.getDL()
Return the Sensor data. position the array to store the sensor data the sensor data.
Referenced by ca.mcgill.ecse211.lab5.Display.run, ca.mcgill.ecse211.lab5.LightLocalizer.localize, ca.mcgill.ecse211.lab5.Navigation.travelTo, ca.mcgill.ecse211.lab5.UltrasonicLocalizer.localize.
int [][] ca.mcgill.ecse211.sensors.SensorData.getRGB()
get the rgb data for color sensor: rgb data
Referenced by ca.mcgill.ecse211.lab5.Display.run.
double ca.mcgill.ecse211.sensors.SensorData.getA()
This method returns the currently stored angle valueThe current angle value
Referenced by ca.mcgill.ecse211.lab5.Display.run, ca.mcgill.ecse211.lab5.Navigation.travelTo, ca.mcgill.ecse211.lab5.Navigation.turnTo.
void ca.mcgill.ecse211.sensors.SensorData.setD(double d)
This method overwrites the distance value. Use for ultrasonic sensor. d The value to overwrite distance with
Referenced by ca.mcgill.ecse211.sensors.UltrasonicPoller.run.
void ca.mcgill.ecse211.sensors.SensorData.setA(double a)
This method overwrites the angle value. a The value to overwrite angle with
Referenced by ca.mcgill.ecse211.sensors.GyroPoller.run.
void ca.mcgill.ecse211.sensors.SensorData.setRGB(int i, int r, int g, int b)
set rgb data for color sensor with specific id i id for the color sensor r red value g green value b blue value
Referenced by ca.mcgill.ecse211.sensors.RGBPoller.RGBPoller.
void ca.mcgill.ecse211.sensors.SensorData.setL(double l)
This method overwrites the light value. l The value to overwrite the current light value with
Referenced by ca.mcgill.ecse211.sensors.LightPoller.run.