ca::mcgill::ecse211::odometer::Odometer
OdometerData ca.mcgill.ecse211.odometer.Odometer.odoData
int ca.mcgill.ecse211.odometer.Odometer.leftMotorTachoCount
int ca.mcgill.ecse211.odometer.Odometer.rightMotorTachoCount
EV3LargeRegulatedMotor ca.mcgill.ecse211.odometer.Odometer.leftMotor
EV3LargeRegulatedMotor ca.mcgill.ecse211.odometer.Odometer.rightMotor
double ca.mcgill.ecse211.odometer.Odometer.TRACK
double ca.mcgill.ecse211.odometer.Odometer.WHEEL_RAD
double [] ca.mcgill.ecse211.odometer.Odometer.position
Odometer ca.mcgill.ecse211.odometer.Odometer.odometer
final long ca.mcgill.ecse211.odometer.Odometer.ODOMETER_PERIOD
ca.mcgill.ecse211.odometer.Odometer.Odometer(EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor, final double TRACK, final double WHEEL_RAD)
This is the default constructor of this class. It initiates all motors and variables once.It cannot be accessed externally. leftMotor The EV3LargeRegulatedMotor instance for our left motor rightMotor The EV3LargeRegulatedMotor instance for our right motor OdometerExceptions
static synchronized Odometer ca.mcgill.ecse211.odometer.Odometer.getOdometer(EV3LargeRegulatedMotor leftMotor, EV3LargeRegulatedMotor rightMotor, final double TRACK, final double WHEEL_RAD)
This method is meant to ensure only one instance of the odometer is used throughout the code. leftMotor The EV3LargeRegulatedMotor instance for our left motor rightMotor The EV3LargeRegulatedMotor instance for our right motor new or existing Odometer Object OdometerExceptions
Referenced by ca.mcgill.ecse211.lab5.Display.Display, ca.mcgill.ecse211.lab5.Lab5.main, ca.mcgill.ecse211.lab5.LightLocalizer.LightLocalizer, ca.mcgill.ecse211.lab5.Navigation.Navigation, ca.mcgill.ecse211.lab5.RingSearcher.RingSearcher, ca.mcgill.ecse211.lab5.UltrasonicLocalizer.UltrasonicLocalizer, ca.mcgill.ecse211.odometer.OdometryCorrection.OdometryCorrection.
static synchronized Odometer ca.mcgill.ecse211.odometer.Odometer.getOdometer()
This class is meant to return the existing Odometer Object. It is meant to be used only if an odometer object has been createderror if no previous odometer exists
void ca.mcgill.ecse211.odometer.Odometer.run()
This method is called when our Odometer object is started as a thread and begins to keep track of motor rotations
References ca.mcgill.ecse211.odometer.OdometerData.getXYT, ca.mcgill.ecse211.odometer.OdometerData.update, ca.mcgill.ecse211.lab5.Lab5.TILE.