.TH "ca.mcgill.ecse211.odometer" 3 "Tue Oct 23 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.odometer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOdometer\fP"
.br
.ti -1c
.RI "class \fBOdometerData\fP"
.br
.ti -1c
.RI "class \fBOdometerExceptions\fP"
.br
.ti -1c
.RI "class \fBOdometryCorrection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is meant as a skeleton for the odometer class to be used\&.
.PP
\fBAuthor:\fP
.RS 4
Rodrigo Silva 
.PP
Dirk Dubois 
.PP
Derek Yu 
.PP
Karim El-Baba 
.PP
Michael Smith 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
