.TH "ca.mcgill.ecse211.odometer.OdometryCorrection" 3 "Mon Oct 22 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.odometer.OdometryCorrection
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOdometryCorrection\fP ()  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements correction for the odometry on our robot using a light sensor\&.
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro & Patrick Erath 
.RE
.PP

.PP
Definition at line 16 of file OdometryCorrection\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.odometer\&.OdometryCorrection\&.OdometryCorrection () throws \fBOdometerExceptions\fP"
This is the default class constructor\&. An existing instance of the odometer is used\&. This is to ensure thread safety\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBOdometerExceptions\fP\fP 
.RE
.PP

.PP
Definition at line 29 of file OdometryCorrection\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.odometer\&.OdometryCorrection\&.run ()"
Here is where the odometer correction code should be run\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBOdometerExceptions\fP\fP 
.RE
.PP

.PP
Definition at line 40 of file OdometryCorrection\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
