.TH "ca.mcgill.ecse211.odometer.OdometerExceptions" 3 "Tue Oct 23 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.odometer.OdometerExceptions
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOdometerExceptions\fP (String Error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to handle errors regarding the singleton pattern used for the odometer and odometerData
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro & Percy Chen & Patrick Erath & Anssam Ghezala & Susan Matuszewski & Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 11 of file OdometerExceptions\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.odometer\&.OdometerExceptions\&.OdometerExceptions (String Error)"
This is an \fBOdometerExceptions\fP class constructor that accepts a descriptive error message\&.
.PP
\fBParameters:\fP
.RS 4
\fIError\fP a String that contains an error message 
.RE
.PP

.PP
Definition at line 17 of file OdometerExceptions\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
