.TH "ca.mcgill.ecse211.sensors.SensorData" 3 "Wed Oct 24 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.sensors.SensorData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double [] \fBgetDL\fP ()"
.br
.ti -1c
.RI "int [][] \fBgetRGB\fP ()"
.br
.ti -1c
.RI "double \fBgetA\fP ()"
.br
.ti -1c
.RI "void \fBsetD\fP (double d)"
.br
.ti -1c
.RI "void \fBsetA\fP (double a)"
.br
.ti -1c
.RI "void \fBsetRGB\fP (int i, int r, int g, int b)"
.br
.ti -1c
.RI "void \fBsetL\fP (double l)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static synchronized \fBSensorData\fP \fBgetSensorData\fP ()  throws OdometerExceptions "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSensorData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements methods to manage data from our sensors
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 18 of file SensorData\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.SensorData ()\fC [protected]\fP"
Default constructor\&. The constructor is private\&. A factory is used instead such that only one instance of this class is ever created\&. 
.PP
Definition at line 49 of file SensorData\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.getA ()"
This method returns the currently stored angle value
.PP
\fBReturns:\fP
.RS 4
The current angle value 
.RE
.PP

.PP
Definition at line 136 of file SensorData\&.java\&.
.SS "double [] ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.getDL ()"
Return the Sensor data\&.
.PP
\fBParameters:\fP
.RS 4
\fIposition\fP the array to store the sensor data 
.RE
.PP
\fBReturns:\fP
.RS 4
the sensor data\&. 
.RE
.PP

.PP
Definition at line 90 of file SensorData\&.java\&.
.SS "int [][] ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.getRGB ()"
get the rgb data for color sensor
.PP
\fBReturns:\fP
.RS 4
: rgb data 
.RE
.PP

.PP
Definition at line 117 of file SensorData\&.java\&.
.SS "static synchronized \fBSensorData\fP ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.getSensorData () throws \fBOdometerExceptions\fP\fC [static]\fP"
OdometerData factory\&. Returns an OdometerData instance and makes sure that only one instance is ever created\&. If the user tries to instantiate multiple objects, the method throws a MultipleOdometerDataException\&.
.PP
\fBReturns:\fP
.RS 4
An OdometerData object 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 70 of file SensorData\&.java\&.
.SS "void ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.setA (double a)"
This method overwrites the angle value\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP The value to overwrite angle with 
.RE
.PP

.PP
Definition at line 173 of file SensorData\&.java\&.
.SS "void ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.setD (double d)"
This method overwrites the distance value\&. Use for ultrasonic sensor\&.
.PP
\fBParameters:\fP
.RS 4
\fId\fP The value to overwrite distance with 
.RE
.PP

.PP
Definition at line 155 of file SensorData\&.java\&.
.SS "void ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.setL (double l)"
This method overwrites the light value\&.
.PP
\fBParameters:\fP
.RS 4
\fIl\fP The value to overwrite the current light value with 
.RE
.PP

.PP
Definition at line 214 of file SensorData\&.java\&.
.SS "void ca\&.mcgill\&.ecse211\&.sensors\&.SensorData\&.setRGB (int i, int r, int g, int b)"
set rgb data for color sensor with specific id
.PP
\fBParameters:\fP
.RS 4
\fIi\fP id for the color sensor 
.br
\fIr\fP red value 
.br
\fIg\fP green value 
.br
\fIb\fP blue value 
.RE
.PP

.PP
Definition at line 194 of file SensorData\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
