.TH "ca.mcgill.ecse211.sensors.GyroPoller" 3 "Wed Oct 24 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.sensors.GyroPoller
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGyroPoller\fP (SampleProvider us, float[] lgData, \fBSensorData\fP cont)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGyroPoller\fP \fBInstance\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBprocessData\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SampleProvider \fBus\fP"
.br
.ti -1c
.RI "\fBSensorData\fP \fBcont\fP"
.br
.ti -1c
.RI "float [] \fBlgData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class helps our robot to navigate using a gyroscope
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 16 of file GyroPoller\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.sensors\&.GyroPoller\&.GyroPoller (SampleProvider us, float [] lgData, \fBSensorData\fP cont) throws \fBOdometerExceptions\fP"
This constructor creates an instance of the \fBGyroPoller\fP class to aid navigation
.PP
\fBParameters:\fP
.RS 4
\fIus\fP A SampleProvider class instance that helps us to store an array of ultrasonic sensor data\&. 
.br
\fIlgData\fP An array used to store data\&. 
.br
\fIcont\fP A \fBSensorData\fP object instance used to manage sensor data\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 31 of file GyroPoller\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.sensors\&.GyroPoller\&.run ()"
This method is called by a \fBUltrasonicPoller\fP (Thread) instance when it is asked to start executing
.PP
Sensors now return floats using a uniform protocol\&. Need to convert US result to an integer [0,255] (non-Javadoc)
.PP
\fBSee also:\fP
.RS 4
java\&.lang\&.Thread::run() 
.RE
.PP

.PP
Definition at line 46 of file GyroPoller\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
