.TH "ca.mcgill.ecse211.lab5.Display" 3 "Tue Oct 23 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.lab5.Display
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplay\fP (TextLCD lcd)  throws OdometerExceptions "
.br
.ti -1c
.RI "\fBDisplay\fP (TextLCD lcd, long timeout)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to display the content of the odometer variables (x, y, Theta)
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro & Percy Chen & Patrick Erath & Anssam Ghezala & Susan Matuszewski & Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 15 of file Display\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.Display (TextLCD lcd) throws \fBOdometerExceptions\fP"
This is the class constructor
.PP
\fBParameters:\fP
.RS 4
\fIodoData\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 32 of file Display\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.Display (TextLCD lcd, long timeout) throws \fBOdometerExceptions\fP"
This is the overloaded class constructor
.PP
\fBParameters:\fP
.RS 4
\fIodoData\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 44 of file Display\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.run ()"
This method is called when the \fBDisplay\fP thread is started\&. 
.PP
Definition at line 53 of file Display\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
