.TH "ca.mcgill.ecse211.lab5.Display" 3 "Wed Oct 24 2018" "Version 1.0" "ECSE211 - Fall 2018 - Lab 5 - Search and Localize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ca.mcgill.ecse211.lab5.Display
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplay\fP (TextLCD lcd)  throws OdometerExceptions "
.br
.ti -1c
.RI "\fBDisplay\fP (TextLCD lcd, long timeout)  throws OdometerExceptions "
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is used to display the content of the odometer variables (x, y, Theta)
.PP
\fBAuthor:\fP
.RS 4
Caspar Cedro 
.PP
Percy Chen 
.PP
Patrick Erath 
.PP
Anssam Ghezala 
.PP
Susan Matuszewski 
.PP
Kamy Moussavi Kafi 
.RE
.PP

.PP
Definition at line 19 of file Display\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.Display (TextLCD lcd) throws \fBOdometerExceptions\fP"
This is the class constructor for a display object that controls an EV3 brick display
.PP
\fBParameters:\fP
.RS 4
\fIlcd\fP A TextLCD object instance to control 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 35 of file Display\&.java\&.
.SS "ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.Display (TextLCD lcd, long timeout) throws \fBOdometerExceptions\fP"
This is the overloaded class constructor for a display object
.PP
\fBParameters:\fP
.RS 4
\fIlcd\fP A TextLCD object instance to control 
.br
\fItimeout\fP A duration of time to update the display for 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIOdometerExceptions\fP 
.RE
.PP

.PP
Definition at line 48 of file Display\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void ca\&.mcgill\&.ecse211\&.lab5\&.Display\&.run ()"
This method is called when the \fBDisplay\fP thread is started\&. 
.PP
Definition at line 57 of file Display\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ECSE211 - Fall 2018 - Lab 5 - Search and Localize from the source code\&.
